name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1
        with:
          repository: glsorre/lares4-ts
          preRelease: ${{ contains(github.event.release.tag_name, 'beta') }}
          tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GH_TOKEN }}
          zipBall: true
          extract: true

      - name: Change directory
        run: cd /home/runner/work/lares4-ts/lares4-ts

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: v22.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Publish package on NPM
        if: ${{ !contains(github.event.release.ref_name, 'beta') }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish beta package on NPM
        if: ${{ contains(github.event.release.ref_name, 'beta') }}
        run: npm publish --beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}